name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${{ github.sha }} .
      working-directory: ./java_sqs_client

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${{ github.sha }}

    - name: Tag Docker image with latest and branch
      run: |
        BRANCH_TAG=${{ github.ref_name }}
        BRANCH_TAG=$(echo $BRANCH_TAG | sed 's/\//-/g')  # Replace '/' with '-'
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${BRANCH_TAG}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/eksamendevopskandidat35:${BRANCH_TAG}
