name: Terraform Deployment

on:
  push:
    branches:
      - main
      - '*'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'
      USER_EMAIL: ${{ github.actor }}@users.noreply.github.com

    steps:

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: /infra

      - name: Terraform Plan
        run: terraform plan -var 'alert_email=${{ env.USER_EMAIL }}'
        working-directory: /infra

      - name: Terraform Apply
        run: terraform apply -var 'alert_email=${{ env.USER_EMAIL }}' -auto-approve
        working-directory: /infra